name: Auto Approve

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      if: startsWith(github.actor, 'dependabot')
      with:
        github-token: "${{ secrets.github_token }}"
