name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions-rs/cargo@master
        with:
          command: install
          args: rojo

      - name: Install NodeJS
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install node_modules
        run: |
          npm install -g roblox-ts
          npm install @rbxts/types

      - run: rbxtsc

      - run: rojo build -o model.rbxmx

      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./model.rbxmx
          asset_name: model.rbxmx
          asset_content_type: application/octet-stream