name: Build

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions-rs/cargo@master
        with:
          command: install
          args: rojo

      - name: Install NodeJS
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install node_modules
        run: |
          npm install -g roblox-ts
          npm install @rbxts/types

      - run: rbxtsc

      - run: rojo build -o model.rbxmx

      - name: GitHub Releases
        uses: fnkr/github-action-ghr@v1.1
        env:
          GHR_PATH: "./model.rbxmx"
          GITHUB_TOKEN: ${{ secrets.github_token }}
