name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    if: github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest

    steps:
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: rojo

      - name: Install NodeJS
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install node_modules
        run: |
          npm install -g roblox-ts
          npm install @rbxts/types

      - run: rbxtsc

      - run: sudo apt install tree >/dev/null && tree
      - run: rojo -V

      - run: rojo build -o model.rbxmx

      - name: GitHub Releases
        uses: fnkr/github-action-ghr@v1.1
        with:
          GHR_PATH: model.rbxmx
          GITHUB_TOKEN: ${{ secrets.github_token }}
